language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: friends-quotes-api
  skip_cleanup: true
  api_key:
    secure: H9W6oCsqWpGtOTm3trZ61oWw8UmBuRog6i8JI5nn/3ZQSlNKVIJCv8bIFMtMPwwdrNsFuo1R3ZPJ93KYyNm8hQ19rnpz8YX07pJUyavPNpB8gCGrjEeJ9O1JvKw91u9dqjLLNK9PdkRym20GpzHPqjbL/1BvAFnswWqwfZTljYXHxcVNVBwObLbggmWU9QkoVF6It12MeWdr6H4IkGuolxQemoHn4S1FILviyXBKQTuskGP6ktypnAuijYpr25OSF2cGLZrH2f2tF0bl1clEzv1IzGAkwlojM8M+gKWYfCZRWhLPP61x4HpnMZ8XjSNdjg3xya5S20Ta0T/cnZWHdM8gDeBt+94wqNmwuvv8GzA9uwqgusOyjN1CgFdLQdnhplRcdIn8lJPt88SGqu1EY0hKgoieM6qmtJZ6854kWVwKk1jJm+3i4rDAhafJZuOpXm8z2By58TVxclwUuOu/hOiflIJftgpQSf54DEoD6qgJM+Hbxyg2J14X8IAzh0rDW+KNdfzNdoySldVx2TakPky6a5eyqNDvR4Mx0h6qHMS/HHwBs1ae30+ox2c29T4ndq+vd0xH7vG65mwzvsucSFkLY4qvrBVtOZQshe1E2wrAT+RvcCHgdXFpoRnjjjfR6H90be6Fv9VSteUTVymXltYunqie3hhWp1YmdS2gE5I=
